In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import plotly.graph_objects as go

from scipy.spatial import distance


from cities.utils.data_grabber import DataGrabber
data = DataGrabber()

from cities.utils.fips_query import FipsQuery

In [2]:
f1007 = FipsQuery(fips = 1007, outcome_var= "gdp",
                  feature_groups= ["population"],
                  lag = 0, top = 8)

print(
"outcome", f1007.outcome_var, "\n"
"feature_groups", f1007.feature_groups, "\n",
"weights", f1007.weights, "\n",
"data_names", f1007.data.std_wide.keys(), "\n",
)

display(f1007.data.std_wide['gdp'].shape)

display(f1007.data.std_wide['population'].shape)


outcome gdp 
feature_groups ['population'] 
 weights [4] 
 data_names dict_keys(['gdp', 'population']) 



(3106, 22)

(3106, 31)

In [3]:

f1007.find_euclidean_kins()

#display(f1007.outcome_slices['my_array'].shape[0])
#display(f1007.outcome_slices['other_arrays'].shape[1])


extracting feature population


(1, 29)

(20,)

array([[-0.78873273, -0.78755832, -0.78429717, -0.78301919, -0.77974975,
        -0.77711631, -0.77170594, -0.78121934, -0.77125959, -0.77012895,
        -0.77060342, -0.76941006, -0.76856231, -0.77015477, -0.76893744,
        -0.76772764, -0.76804302, -0.77041696, -0.77353702, -0.77602021,
        -0.77940007, -0.78059043, -0.78195663, -0.78331559, -0.7854498 ,
        -0.78876226, -0.78958375, -0.79182952, -0.78996084]])

array([-0.0693591421667336, -0.0805169470860766, -0.0641080977387719,
       -0.0393383892430093, -0.0736506577761759, -0.077012563983248,
       -0.0187948286549189, -0.0303993992999194, -0.0398934376475348,
       0.003457338631457, 0.012173801023225, -0.0739180884438521,
       -0.1065589174967108, -0.1806138451198566, -0.15887226272186,
       -0.1652530371916225, -0.1776490534049165, -0.0896704815833897,
       -0.0029813274752864, -0.0624655991193373], dtype=object)

array([[-0.0693591421667336, -0.0805169470860766, -0.0641080977387719,
        -0.0393383892430093, -0.0736506577761759, -0.077012563983248,
        -0.0187948286549189, -0.0303993992999194, -0.0398934376475348,
        0.003457338631457, 0.012173801023225, -0.0739180884438521,
        -0.1065589174967108, -0.1806138451198566, -0.15887226272186,
        -0.1652530371916225, -0.1776490534049165, -0.0896704815833897,
        -0.0029813274752864, -0.0624655991193373, -0.7887327315823498,
        -0.787558324056749, -0.7842971718024482, -0.7830191949891949,
        -0.7797497519190629, -0.7771163126324809, -0.7717059361137736,
        -0.7812193428202951, -0.7712595890485701, -0.7701289515207573,
        -0.7706034204582124, -0.7694100618354813, -0.7685623097422503,
        -0.7701547677440226, -0.7689374367029741, -0.7677276410671973,
        -0.768043015116161, -0.7704169564297161, -0.7735370227901726,
        -0.776020206022187, -0.7794000687318965, -0.7805904296247236,
        -0.78195

In [4]:
# Suppose you want to find the most similar cities to a given city, but with some lag.
# "What places were on a similar path lag years ago?"

f1007 = FipsQuery(1007,lag = 2)
f1007.find_euclidean_kins()
f1007.plot_kins()
#display(f1007.euclidean_kins.head(n = 8))

TypeError: object of type 'NoneType' has no len()

In [ ]:
# Suppose you want lag = 0
# What locations are in the same place as us now?"
# Also, say you want 8 candidates.
f1007 = FipsQuery(1007, lag = 0, top = 8)
f1007.find_euclidean_kins()
f1007.plot_kins()

In [ ]:
# Suppose you want to access all the data, ranked by similarity

#TODO_Nikodem, this needs to spit out the original values, not the scaled ones

display(f1007.euclidean_kins.head())

GeoFIPS          GeoName      2001      2002      2003      2004  \
894     20029        Cloud, KS -0.059316 -0.132529 -0.051459 -0.030684   
613     17053         Ford, IL -0.106839 -0.075933 -0.079730 -0.033871   
2515    48001     Anderson, TX  0.002178 -0.003158 -0.047587 -0.084958   
919     20079       Harvey, KS -0.078521 -0.060924 -0.055260 -0.020984   
1879    36119  Westchester, NY -0.047057 -0.070532 -0.073784 -0.037280   

          2005      2006      2007      2008  ...      2013      2014  \
894  -0.056902 -0.027023  0.002188  0.070613  ... -0.080622 -0.065057   
613  -0.087358 -0.104500 -0.029465  0.026515  ...  0.004072 -0.032732   
2515 -0.102350 -0.026491  0.010768  0.010167  ... -0.110920 -0.128344   
919  -0.058141 -0.040019 -0.067885 -0.009077  ... -0.056148 -0.114546   
1879 -0.065338 -0.064127 -0.047485 -0.041928  ... -0.091409 -0.085667   

          2015      2016      2017      2018      2019      2020      2021  \
894  -0.138615 -0.138637 -0.200075 -0.164736 -0.100996 -0.037332 -0.064526   
613  -0.164663 -0.086840 -0.199359 -0.167660 -0.141072 -0.022478 -0.075714   
2515 -0.198133 -0.152208 -0.136677 -0.104987 -0.071207 -0.057417 -0.015335   
919  -0.132910 -0.135098 -0.172021 -0.093091 -0.091850 -0.108204 -0.076687   
1879 -0.113793 -0.096560 -0.097071 -0.083823 -0.058048 -0.057861 -0.046030   

      distance to 1007  
894           0.159140  
613           0.180235  
2515          0.186440  
919           0.187845  
1879          0.188640  

[5 rows x 23 columns]

In [ ]:
f12011 = FipsQuery(12011, lag = 0, top = 8)